import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, Case, Output, Run } from "./api";
import "./styles.css";

const icon = (name:string) => <span className="material-symbols-outlined">{name}</span>;
const money = (value?:number) => new Intl.NumberFormat("pt-BR", {style:"currency", currency:"BRL"}).format(value || 0);
const date = (value?:string) => value ? new Intl.DateTimeFormat("en-GB", {dateStyle:"medium", timeStyle:"short"}).format(new Date(value)) : "-";
const issue = (value?:string) => (value || "Awaiting investigation").replaceAll("_", " ");

function Badge({children, tone="slate"}:{children:React.ReactNode;tone?:string}) { return <span className={`badge ${tone}`}>{children}</span>; }
function Status({value}:{value?:string}) { const state=value || "not_started"; return <Badge tone={state === "completed" || state === "approved" ? "green" : state === "failed" || state === "rejected" ? "red" : state === "running" ? "blue" : "slate"}>{state.replaceAll("_", " ")}</Badge>; }

export default function App() {
  const [cases, setCases] = useState<Case[]>([]); const [selected, setSelected] = useState<string | null>(null); const [detail, setDetail] = useState<{case:Case;runs:Run[]}|null>(null); const [screen, setScreen] = useState<"cases"|"detail"|"new">("cases"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = async () => { setLoading(true); try { const data=await api.cases(); setCases(data.items); } catch(e:any) { setError(e.message); } finally {setLoading(false);} };
  useEffect(()=>{refresh();},[]);
  const open = async (id:string) => { setSelected(id); setScreen("detail"); try {setDetail(await api.case(id));} catch(e:any){setError(e.message);} };
  const currentRun = detail?.runs[0];
  useEffect(()=>{ if (screen!=="detail" || !currentRun || currentRun.status!=="running") return; const timer=setInterval(async()=>{const next=await api.case(detail!.case.case_id); setDetail(next); if(next.runs[0]?.status!=="running") refresh();},2000); return()=>clearInterval(timer); },[screen, currentRun?.run_id, currentRun?.status]);
  return <div className="app"><aside><div className="brand"><div className="mark">O</div><div><strong>olist</strong><small>DISPUTE DESK</small></div></div><nav><button className={screen==="cases"||screen==="detail"?"active":""} onClick={()=>setScreen("cases")}>{icon("folder_open")} Cases</button><button onClick={()=>setScreen("new")}>{icon("add_circle")} Run investigation</button></nav><div className="sidebar-bottom"><div className="user">{icon("support_agent")} <span>Support operations<small>Internal workspace</small></span></div></div></aside>
  <main><header><div><p className="eyebrow">OPERATIONS / DISPUTES</p><h1>{screen==="new"?"New investigation":screen==="detail"?detail?.case.case_id || "Case file":"Cases"}</h1></div><div className="header-actions"><span className="api-dot"><i/> API connected</span><button className="icon-button" title="Refresh" onClick={refresh}>{icon("refresh")}</button><button className="primary" onClick={()=>setScreen("new")}>{icon("add")} New case</button></div></header>
  {error && <div className="alert">{icon("error")} {error}<button onClick={()=>setError("")}>Dismiss</button></div>}
  {screen==="cases" && <CasesView cases={cases} loading={loading} open={open} create={()=>setScreen("new")}/>} {screen==="detail" && detail && <DetailView detail={detail} setDetail={setDetail} refresh={refresh} goBack={()=>setScreen("cases")}/>} {screen==="new" && <NewCase onCreated={(id)=>open(id)} cancel={()=>setScreen("cases")}/>}</main></div>;
}

function CasesView({cases,loading,open,create}:{cases:Case[];loading:boolean;open:(id:string)=>void;create:()=>void}) { const [filter,setFilter]=useState(""); const rows=useMemo(()=>cases.filter(c=>`${c.case_id} ${c.order_id} ${c.customer_message}`.toLowerCase().includes(filter.toLowerCase())),[cases,filter]); return <section className="content"><div className="toolbar"><div className="search">{icon("search")}<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search case, order or customer claim"/></div><button className="secondary">{icon("tune")} Filters</button><span className="count">{rows.length} case{rows.length===1?"":"s"}</span></div><div className="panel table-wrap"><table><thead><tr><th>CASE</th><th>CUSTOMER CLAIM</th><th>ASSESSMENT</th><th>REFUND</th><th>RUN STATUS</th><th>DECISION</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={7} className="empty">Loading cases...</td></tr>:rows.length?rows.map(c=><tr key={c.case_id} onClick={()=>open(c.case_id)}><td><strong>{c.case_id}</strong><small>{c.order_id.slice(0,12)}...</small></td><td className="claim">{c.customer_message}</td><td><span className="issue">{issue(c.final_output?.assessment.primary_issue)}</span><small>{c.final_output ? `${Math.round(c.final_output.assessment.confidence*100)}% confidence` : "No assessment yet"}</small></td><td className="numeric">{c.final_output ? money(c.final_output.financial_resolution.recommended_refund_brl) : "-"}</td><td><Status value={c.run_status}/></td><td><Status value={c.decision}/></td><td>{icon("chevron_right")}</td></tr>):<tr><td colSpan={7} className="empty"><h3>No cases yet</h3><p>Create a case from an Olist order to begin.</p><button className="primary" onClick={create}>New case</button></td></tr>}</tbody></table></div></section> }

function DetailView({detail,setDetail,refresh,goBack}:{detail:{case:Case;runs:Run[]};setDetail:(d:any)=>void;refresh:()=>void;goBack:()=>void}) { const [tab,setTab]=useState("assessment"); const c=detail.case; const run=detail.runs[0]; const output=run?.final_output; const rerun=async()=>{try{await api.run(c.case_id);setDetail(await api.case(c.case_id));refresh();}catch(e:any){alert(e.message)}}; const decide=async(decision:string)=>{try{const updated=await api.decide(c.case_id,decision);setDetail({...detail,case:{...c,...updated}});refresh();}catch(e:any){alert(e.message)}}; return <section className="content detail"><div className="case-bar"><div><button className="back" onClick={goBack}>{icon("arrow_back")} Cases</button><div className="title-row"><h2>{c.case_id}</h2><Status value={run?.status}/><Status value={c.decision}/></div><p>Order <code>{c.order_id}</code> · opened {date(c.opened_at)}</p></div><div className="actions"><button className="secondary" onClick={rerun} disabled={run?.status==="running"}>{icon("play_arrow")} {run?"Run again":"Run investigation"}</button>{output && c.decision==="pending" && <><button className="secondary danger" onClick={()=>decide("rejected")}>{icon("close")} Reject</button><button className="primary" onClick={()=>decide("approved")}>{icon("check")} Approve recommendation</button></>}</div></div><Pipeline run={run}/><div className="tabs"><button className={tab==="assessment"?"selected":""} onClick={()=>setTab("assessment")}>Assessment</button><button className={tab==="evidence"?"selected":""} onClick={()=>setTab("evidence")}>Evidence board</button><button className={tab==="agents"?"selected":""} onClick={()=>setTab("agents")}>Agent reports</button><button className={tab==="timeline"?"selected":""} onClick={()=>setTab("timeline")}>Run timeline</button></div>{run?.status==="running"?<div className="running panel"><div className="spinner"/><h3>Investigating this case</h3><p>Order, payment and delivery specialists are gathering evidence in parallel.</p></div>:run?.status==="failed"?<div className="alert error-panel">{icon("error")} Investigation failed: {run.error_message}</div>:!run?<div className="empty panel"><h3>Ready to investigate</h3><p>Run the investigation to get a deterministic policy recommendation.</p><button className="primary" onClick={rerun}>Run investigation</button></div>:tab==="assessment"?<Assessment output={output} claim={c.customer_message}/>:tab==="evidence"?<Evidence run={run}/>:tab==="agents"?<Reports run={run}/>:<Timeline run={run}/>}</section> }
function Pipeline({run}:{run?:Run}) { const steps=["Coordinator","Order & seller","Payment","Delivery","Evidence","Policy","Verifier"]; const state=run?.status; return <div className="pipeline">{steps.map((step,i)=><div className={`step ${state==="completed"?"done":state==="running"&&i<4?"working":""}`} key={step}><span>{state==="completed"?icon("check"):i+1}</span><label>{step}</label></div>)}</div> }
function Assessment({output,claim}:{output?:Output;claim:string}) { if(!output) return <div className="empty panel">No verified output is available.</div>; const a=output.assessment, f=output.financial_resolution; return <div className="assessment-grid"><div className="panel outcome"><p className="eyebrow">VERIFIED ASSESSMENT</p><h2>{issue(a.primary_issue)}</h2><Badge tone={a.case_status==="action_required"?"amber":"slate"}>{a.case_status.replaceAll("_"," ")}</Badge><div className="confidence"><span>Confidence</span><strong>{Math.round(a.confidence*100)}%</strong><div><i style={{width:`${a.confidence*100}%`}}/></div></div><div className="cause"><p>Primary cause</p><strong>{output.root_cause_analysis.ranked_causes[0]?.cause_code?.replaceAll("_"," ")}</strong></div></div><div className="panel refund"><p className="eyebrow">RECOMMENDED REFUND</p><h2>{money(f.recommended_refund_brl)}</h2><p>of {money(f.payment_total_brl)} collected</p><hr/><dl><div><dt>Item value</dt><dd>{money(f.item_total_brl)}</dd></div><div><dt>Freight</dt><dd>{money(f.freight_total_brl)}</dd></div><div><dt>Resolution</dt><dd>{output.resolution_actions[0]?.replaceAll("_"," ")}</dd></div></dl></div><div className="panel span-two"><h3>Responsible parties</h3><div className="parties">{output.root_cause_analysis.responsible_parties.length?output.root_cause_analysis.responsible_parties.map((p,i)=><div key={i}>{icon(p.party_type==="seller"?"storefront":"local_shipping")}<span><strong>{p.party_type.replaceAll("_"," ")}</strong><small>{p.party_id}</small></span></div>):<p>No external party is responsible.</p>}</div></div><div className="panel span-two"><h3>Customer claim</h3><p className="quote">“{claim}”</p></div></div> }
function Evidence({run}:{run:Run}) { const board=run.evidence_board; const ids=board?.evidence_ids || run.final_output?.evidence_ids || []; return <div className="panel evidence"><div><p className="eyebrow">VERIFIED FACTS</p>{board?.verified_facts ? Object.entries(board.verified_facts).map(([k,v])=><div className="fact" key={k}><span>{k.replaceAll("_"," ")}</span><strong>{Array.isArray(v)?v.join(", ")||"None":String(v)}</strong></div>):<p>No evidence board snapshot available.</p>}</div><div><p className="eyebrow">EVIDENCE REFERENCES</p>{ids.map((id:string)=><code className="evidence-id" key={id}>{id}</code>)}<p className="muted">Evidence IDs resolve to source records in the Olist system of record.</p></div></div> }
function Reports({run}:{run:Run}) { const reports=run.reports||{}; return <div className="reports">{Object.entries(reports).map(([name,report])=><details className="panel" key={name}><summary>{icon("smart_toy")} {name.replaceAll("_"," ")}{icon("expand_more")}</summary><pre>{JSON.stringify(report,null,2)}</pre></details>)}</div> }
function Timeline({run}:{run:Run}) { return <div className="timeline panel">{run.timeline?.length?run.timeline.map((event,i)=><div className="event" key={i}><i/><div><strong>{event.event?.replaceAll("_"," ")}</strong><p>{event.agent || event.message || event.status || "System event"}</p></div><time>{date(event.timestamp)}</time></div>):<p>No timeline data was saved.</p>}</div> }
function NewCase({onCreated,cancel}:{onCreated:(id:string)=>void;cancel:()=>void}) { const [order,setOrder]=useState(""); const [message,setMessage]=useState("Delivery arrived later than expected. Please review my refund request."); const [results,setResults]=useState<any[]>([]); const [saving,setSaving]=useState(false); const search=async(v:string)=>{setOrder(v);if(v.length<2){setResults([]);return;} try{setResults((await api.orders(v)).items)}catch{}}; const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{const c=await api.createCase({order_id:order,customer_message:message,language:"pt-BR"});await api.run(c.case_id);onCreated(c.case_id);}catch(e:any){alert(e.message)}finally{setSaving(false)}}; return <section className="content form-page"><div className="form-intro"><p className="eyebrow">CASE INTAKE</p><h2>Start an investigation</h2><p>Create a case from an existing Olist order. The pipeline will reconcile source records before making a deterministic recommendation.</p></div><form className="panel form" onSubmit={submit}><label>Olist order ID<input value={order} onChange={e=>search(e.target.value)} required placeholder="Search an order ID" autoComplete="off"/></label>{results.length>0&&<div className="order-results">{results.map(o=><button type="button" onClick={()=>{setOrder(o.order_id);setResults([])}} key={o.order_id}><strong>{o.order_id}</strong><span>{o.order_status} · {date(o.order_purchase_timestamp)}</span></button>)}</div>}<label>Customer claim<textarea value={message} onChange={e=>setMessage(e.target.value)} required rows={5}/></label><div className="form-actions"><button type="button" className="secondary" onClick={cancel}>Cancel</button><button className="primary" disabled={saving}>{icon("play_arrow")} {saving?"Creating...":"Create & run investigation"}</button></div></form></section> }
